/** First-party assets generated by scripts/generate-seo-assets.mjs + hero photo. */
import { APEX_TACTICAL, APEX_OBJECTIVE } from './media'

export const APEX_OG = '/og/apex-legends-cheats.jpg'
export const APEX_HERO = '/media/apex-legends-product-hero.webp'
export const APEX_COVER = '/media/apex-legends-product-cover.webp'
export const APEX_SOLDIER_HERO = '/media/apex-legends-soldier-hero.jpg'

export type ImageSeoFields = {
  alt: string
  title: string
  caption: string
}

export const IMAGE_SEO: Record<
  string,
  ImageSeoFields & {
    heroAlt: string
    heroTitle: string
    heroCaption: string
  }
> = {
  'apex-legends': {
    alt: 'Apex Legends cheats product artwork for the battle royale',
    title: 'Apex Legends Cheats Product Details',
    caption: 'Apex Legends ESP, radar, aim assistance and Windows compatibility',
    heroAlt: 'Apex Legends cheats features and PC compatibility',
    heroTitle: 'Apex Legends Cheats Features',
    heroCaption: 'Review Apex Legends ESP, radar, aim features and current status',
  },
}

type PageImage = ImageSeoFields & { src: string }

export const PAGE_IMAGES: Record<
  'home' | 'forums' | 'reviews' | 'faq' | 'support' | 'product',
  PageImage
> = {
  home: {
    src: APEX_SOLDIER_HERO,
    alt: 'Apex Legends squad artwork for the PC battle royale',
    title: 'Apex Legends Cheats for PC',
    caption: 'Apex Legends player ESP, radar and aim feature overview.',
  },
  forums: {
    src: APEX_OBJECTIVE,
    alt: 'Apex Legends cheats setup and status guide artwork',
    title: 'Apex Legends Cheats Guides',
    caption: 'Setup, hotkey and compatibility guides for Apex Legends.',
  },
  reviews: {
    src: APEX_TACTICAL,
    alt: 'Apex Legends cheats product evaluation artwork',
    title: 'Apex Legends Cheats Reviews',
    caption: 'Feature and compatibility feedback for current Apex Legends builds.',
  },
  faq: {
    src: APEX_OBJECTIVE,
    alt: 'Apex Legends cheats frequently asked questions artwork',
    title: 'Apex Legends Cheats FAQ',
    caption: 'Compatibility, feature and setup answers for Apex Legends.',
  },
  support: {
    src: APEX_TACTICAL,
    alt: 'Apex Legends cheats support artwork',
    title: 'Apex Legends Cheats Support',
    caption: 'Delivery, loader and setup support for Apex Legends.',
  },
  product: {
    src: APEX_OBJECTIVE,
    alt: 'Apex Legends ESP radar and aim product artwork',
    title: 'Apex Legends Cheats Features',
    caption: 'Product details for Apex Legends ESP, radar and aim assistance.',
  },
}

export function getGameImage(_slug: string): string {
  return APEX_COVER
}

export function getProductHeroImage(slug: string): string {
  return slug === 'apex-legends' ? APEX_HERO : getGameImage(slug)
}

export function getOgImage(path?: string): string {
  if (!path || path === '/') return PAGE_IMAGES.home.src
  if (path === '/apex-legends-cheats') return PAGE_IMAGES.product.src
  if (path === '/forums') return PAGE_IMAGES.forums.src
  if (path === '/reviews') return PAGE_IMAGES.reviews.src
  if (path === '/faq') return PAGE_IMAGES.faq.src
  if (path === '/support') return PAGE_IMAGES.support.src
  return APEX_OG
}

export function getPageImage(key: keyof typeof PAGE_IMAGES) {
  return PAGE_IMAGES[key]
}

export function getImageAlt(
  slug: string,
  name: string,
  variant: 'catalog' | 'product' = 'catalog',
): string {
  const seo = IMAGE_SEO[slug]
  if (seo) return variant === 'product' ? seo.heroAlt : seo.alt
  return variant === 'product' ? `${name} product details` : `${name} product artwork`
}

export function getImageTitle(
  slug: string,
  name: string,
  variant: 'catalog' | 'product' = 'catalog',
): string {
  const seo = IMAGE_SEO[slug]
  if (seo) return variant === 'product' ? seo.heroTitle : seo.title
  return `${name} product`
}
